image: jekyll/builder:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  
cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle config set path 'vendor'
  - bundle install

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
