markdown:         kramdown
highlighter:      none
permalink: 	  /:title/

title:            "Rafał Masiarek"
description:      "I am devops. Automation and configuration management tools are the foundation of my work"

url:              https://masiarek.pl
baseurl:          "/"

author:
  name:           "Rafał Masiarek"

# socials
gitlab:         https://gitlab.com/rafalmasiarek

# assets
assets:  
  source_maps: false
  compression: false
  gzip: false
  #caching: false
  cachebust: false

# compress
compress_html:
  ignore:
    envs: all
