markdown:         kramdown
highlighter:      rouge

title:            "Rafał Masiarek"
description:      ""

url:              https://masiarek.pl
baseurl:          "/"

author:
  name:           "Rafał Masiarek"

# socials
gitlab:         https://gitlab.com/rafalmasiarek

# assets
assets:  
  source_maps: true
  compression: true
  gzip: false
  destination: "/assets/compressed"
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file
  compress:  
    js: 'uglifier'  
    css: 'sass'  
  defaults:
    integrity:
      {css,img,js}: false
  cdn:
    baseurl: true
    destination: true
    url: https://masiarek.pl
  cachebust: hard 

# compress
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  startings: [html, head, body]
