markdown:         kramdown
highlighter:      none
permalink: 	  /:title/

title:            "Rafał Masiarek"
description:      "I am devops. Automation and configuration management tools are the foundation of my work"

url:              https://masiarek.pl
baseurl:          "/"

author:
  name:           "Rafał Masiarek"

# socials
keybase:        "https://keybase.io/rafalmasiarek"
gitlab:         "https://gitlab.com/rafalmasiarek"
linkedin:       "https://www.linkedin.com/in/rafa%C5%82-masiarek-b45699138"

# assets
assets:  
  source_maps: false
  compression: false
  gzip: false
  #caching: false
  cachebust: false

# compress
compress_html:
  ignore:
    envs: all
