name: Keepalive Action
on:
  schedule:
    - cron: '0 2 * * 6'
jobs:
  workflow-keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
